# Top of file
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4
    working_directory: /src/github.com/DEXTERNATAN/App-Todo-React  
    steps:
      - checkout # checks out the source code
      - run: echo "Hello world"  