# Top of file
version: 2
jobs:  
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout # checks out the source code
      - run:
          name: install
          command: 'curl -k -O -L https://npmjs.org/install.sh | sh'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
          - node_modules
      # run tests!
      - run:
          name: run node tests
          command: npm run test
