# Top of file
version: 2
jobs:
  working_directory: ~/project/App-Todo-React  
  build:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout # checks out the source code
      - run: pwd  