# Top of file
version: 2
jobs:  
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout # checks out the source code
      - run: echo "Hello world"  
      # - run:
      #     name: test
      #     command: npm test